In [1]:
from numpy import exp, array, random, dot


class NeuralNetwork():
    def __init__(self):
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((3, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))


if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()

    print ("Random starting synaptic weights: ")
    print (neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("New synaptic weights after training: ")
    print (neural_network.synaptic_weights)

    # Test the neural network with a new situation.
    print ("Considering new situation [1, 0, 0] -> ?: ")
    print (neural_network.think(array([1, 0, 0])))

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Considering new situation [1, 0, 0] -> ?: 
[0.99993704]


In [2]:
from numpy import array, abs, exp, random, dot, mean
import numpy

girdi = array([[0,0,1],[1,1,1],[1,0,1]])
gerceksonuc = array([[0,1,1]]).T
agirlik =array([[1.0,1.0,1.0]]).T # ilk degerleri rastgele alıyoruz.

for tekrar in range(10000):
    hucredegeri = dot(girdi,agirlik)
    tahmin = 1/(1+exp(-hucredegeri))
    agirlik=agirlik+dot(girdi.T, ((gerceksonuc-tahmin)*tahmin*(1-tahmin)))
    print(str(numpy.mean(numpy.abs(gerceksonuc-tahmin))))

print(1/(1+exp(-dot(array([1,0,0]), agirlik))))


0.2992291246098964
0.296483545848207
0.29363165022315413
0.29069110164618006
0.28766447912598275
0.28453652820173875
0.28127856456316813
0.27785871538569373
0.27425342924031276
0.2704554337944901
0.26647587307096804
0.26234140336228157
0.25808864697763406
0.25375834827515203
0.24939066267483423
0.24502206037565924
0.2406837185985163
0.23640102328730292
0.2321937764372024
0.22807678280156476
0.2240605905353025
0.22015224788928375
0.21635600183748135
0.2126739059794768
0.20910632958199585
0.20565237269995892
0.2023101982852944
0.19907729406346894
0.19595067666348479
0.19292704918666806
0.19000292174814715
0.18717470286650176
0.18443876807311077
0.1817915108230599
0.1792293797208265
0.17674890520801675
0.17434671816920233
0.172019562365784
0.16976430217936164
0.1675779268115639
0.1654575518269241
0.16340041872313996
0.16140389305615044
0.15946546152579938
0.15758272833355258
0.15575341105063217
0.1539753361782712
0.1522464345378678
0.15056473659477998
0.1489283677931306
0.147335543958584


0.04058070176255949
0.040534646888637386
0.040488741872924554
0.04044298591867062
0.040397378234981095
0.04035191803676278
0.04030660454466881
0.04026143698504578
0.04021641458988047
0.04017153659674754
0.04012680224875768
0.040082210794506634
0.040037761488024196
0.03999345358872425
0.039949286361355835
0.03990525907595333
0.03986137100778845
0.03981762143732271
0.039774009650159425
0.039730534936997325
0.03968719659358434
0.03964399392067148
0.03960092622396775
0.039557992814095215
0.03951519300654519
0.03947252612163383
0.039429991484458894
0.03938758842485722
0.03934531627736219
0.0393031743811618
0.039261162080056776
0.03921927872242018
0.039177523661156684
0.03913589625366202
0.03909439586178356
0.039053021851781104
0.03901177359428786
0.03897065046427189
0.038929651840998426
0.03888877710799179
0.038848025652998504
0.03880739686795037
0.03876689014892762
0.03872650489612355
0.03868624051380817
0.038646096410293394
0.03860607199789783
0.03856616669291226
0.03852637991556524
0.038

0.02127481200665977
0.021267746712971113
0.021260688290030545
0.021253636726810632
0.021246592012308746
0.021239554135546904
0.021232523085571286
0.021225498851452963
0.021218481422287033
0.021211470787193015
0.02120446693531437
0.021197469855819093
0.021190479537899033
0.02118349597077014
0.02117651914367219
0.021169549045868968
0.021162585666647794
0.021155628995319985
0.021148679021220612
0.021141735733707947
0.021134799122164306
0.02112786917599488
0.021120945884628827
0.021114029237518334
0.021107119224138837
0.021100215833989123
0.021093319056590922
0.021086428881489344
0.021079545298252112
0.021072668296470195
0.0210657978657575
0.021058933995750314
0.021052076676108044
0.02104522589651277
0.02103838164666903
0.021031543916304112
0.02102471269516738
0.021017887973031214
0.02101106973968997
0.021004257984960462
0.02099745269868176
0.020990653870714904
0.020983861490943254
0.020977075549272323
0.02097029603562925
0.020963522939963463
0.020956756252246207
0.020949995962470425
0.020

0.015275074587947015
0.0152724058814772
0.015269738548923044
0.015267072589114123
0.015264408000881087
0.015261744783055952
0.015259082934472326
0.015256422453965144
0.01525376334037063
0.015251105592526478
0.015248449209271833
0.015245794189446929
0.015243140531893733
0.015240488235455235
0.015237837298976167
0.015235187721302335
0.015232539501280963
0.015229892637760796
0.01522724712959161
0.01522460297562516
0.015221960174713665
0.015219318725711544
0.015216678627474235
0.015214039878858188
0.015211402478721839
0.01520876642592447
0.015206131719327031
0.015203498357791645
0.015200866340181647
0.015198235665362034
0.015195606332198899
0.015192978339559812
0.015190351686313573
0.015187726371330326
0.015185102393481665
0.015182479751640401
0.015179858444680533
0.0151772384714777
0.015174619830908639
0.015172002521851358
0.015169386543185519
0.015166771893791606
0.015164158572551866
0.015161546578349623
0.015158935910069525
0.01515632656659758
0.015153718546821024
0.015151111849628585
0

0.01303072393234384
0.013029054153011968
0.013027385005659217
0.01302571648988936
0.01302404860530663
0.013022381351515441
0.013020714728120381
0.013019048734726734
0.013017383370939987
0.013015718636365775
0.013014054530610266
0.013012391053280106
0.013010728203982039
0.013009065982323237
0.013007404387911203
0.013005743420353827
0.01300408307925939
0.013002423364236362
0.013000764274893625
0.012999105810840468
0.012997447971686315
0.012995790757041312
0.01299413416651548
0.012992478199719609
0.012990822856264428
0.0129891681357613
0.012987514037821968
0.012985860562058157
0.012984207708082248
0.012982555475506835
0.012980903863944862
0.012979252873009703
0.012977602502314861
0.012975952751474425
0.012974303620102537
0.012972655107813943
0.012971007214223612
0.012969359938946894
0.012967713281599237
0.012966067241796775
0.012964421819155811
0.012962777013292884
0.012961132823825003
0.012959489250369424
0.012957846292543854
0.01295620394996625
0.012954562222254771
0.01295292110902826
0

0.011152065152407938
0.01115101140798238
0.011149957958210416
0.01114890480295546
0.011147851942080999
0.011146799375450525
0.01114574710292785
0.011144695124376476
0.011143643439660372
0.011142592048643587
0.011141540951189839
0.011140490147163368
0.011139439636428328
0.011138389418849039
0.011137339494289819
0.011136289862615195
0.011135240523689527
0.011134191477377438
0.011133142723543885
0.011132094262053442
0.011131046092770968
0.011129998215561522
0.011128950630290166
0.011127903336822018
0.011126856335022228
0.011125809624756325
0.011124763205889407
0.011123717078287234
0.01112267124181518
0.011121625696339016
0.011120580441724573
0.011119535477837459
0.011118490804543807
0.011117446421709526
0.01111640232920067
0.011115358526883522
0.011114315014624213
0.011113271792289247
0.01111222885974497
0.011111186216857902
0.011110143863494635
0.011109101799521992
0.011108060024806687
0.011107018539215481
0.011105977342615545
0.011104936434873614
0.01110389581585706
0.011102855485433072

0.010175763455445871
0.010174960081788309
0.010174156896020031
0.010173353898068135
0.010172551087859943
0.010171748465322449
0.010170946030382938
0.010170143782968698
0.010169341723006983
0.010168539850425278
0.010167738165150717
0.010166936667111015
0.010166135356233343
0.010165334232445493
0.010164533295674719
0.01016373254584888
0.010162931982895381
0.01016213160674202
0.01016133141731639
0.010160531414546243
0.010159731598359508
0.01015893196868384
0.010158132525447052
0.010157333268577167
0.010156534198002005
0.010155735313649711
0.010154936615448137
0.01015413810332531
0.010153339777209508
0.0101525416370286
0.010151743682710978
0.010150945914184748
0.01015014833137807
0.010149350934219462
0.010148553722637012
0.01014775669655913
0.010146959855914277
0.010146163200630824
0.010145366730637349
0.010144570445862224
0.010143774346234029
0.010142978431681509
0.010142182702133093
0.010141387157517645
0.010140591797763597
0.01013979662279992
0.01013900163255531
0.010138206826958665
0.0

0.00930780942835934
0.009307192610072791
0.009306575912982519
0.009305959337049181
0.009305342882233107
0.009304726548494941
0.009304110335795143
0.009303494244094296
0.009302878273352992
0.009302262423531866
0.009301646694591383
0.009301031086492271
0.009300415599195233
0.009299800232660796
0.009299184986849751
0.00929856986172268
0.009297954857240399
0.009297339973363688
0.00929672521005319
0.009296110567269643
0.009295496044973926
0.00929488164312693
0.009294267361689265
0.009293653200621919
0.009293039159885741
0.009292425239441583
0.009291811439250276
0.009291197759272804
0.0092905841994702
0.009289970759803137
0.009289357440232878
0.00928874424072019
0.009288131161226218
0.00928751820171181
0.009286905362138166
0.009286292642466344
0.009285680042657294
0.00928506756267228
0.009284455202472161
0.009283842962018328
0.00928323084127166
0.009282618840193532
0.009282006958745053
0.009281395196887435
0.00928078355458181
0.009280172031789512
0.009279560628471585
0.009278949344589602
0.0

0.008710458087950295
0.008709951430264115
0.008709444860011696
0.008708938377167694
0.008708431981707274
0.008707925673605317
0.008707419452836748
0.008706913319376682
0.008706407273200156
0.00870590131428211
0.00870539544259752
0.008704889658121525
0.008704383960829072
0.008703878350695344
0.008703372827695264
0.008702867391804023
0.008702362042996558
0.008701856781248215
0.0087013516065339
0.008700846518828754
0.008700341518107916
0.00869983660434653
0.008699331777519788
0.008698827037602842
0.008698322384570668
0.008697817818398736
0.00869731333906202
0.00869680894653574
0.00869630464079519
0.00869580042181555
0.008695296289571974
0.00869479224403985
0.008694288285194226
0.008693784413010603
0.008693280627463903
0.00869277692852963
0.008692273316183087
0.008691769790399604
0.008691266351154229
0.008690762998422568
0.008690259732179679
0.008689756552401102
0.008689253459062164
0.00868875045213808
0.008688247531604375
0.00868774469743624
0.008687241949609166
0.00868673928809865
0.0086

In [3]:
agirlik

array([[ 8.96031307],
       [ 1.62234651],
       [-4.36676539]])